server.port: 3505
server.address: 0.0.0.0
#ssl
# manual https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.webserver.configure-ssl
server.ssl.enabled: false
#server.ssl.certificate: /home/alekcei/keystore/fullchain.pem
#server.ssl.certificate-private-key: /home/alekcei/keystore/privkey.pem

eureka.client.enabled: false
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

# logging.level.root=info # зашито
logging.access.enabled: true
logging.access.name: './access.log'

####  PROXY SERVICE  ####
spring.cloud.discovery.client.simple.instances.webdav[0].uri: https://webdav.yandex.ru

# router settings
spring.cloud.gateway.routes[0].id: OtherAll
spring.cloud.gateway.routes[0].order: 1001
spring.cloud.gateway.routes[0].predicates[0]: Path=/**
spring.cloud.gateway.routes[0].uri: lb://webdav
